[package]
name = "speedy-softmax"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.2.0" }
candle-nn = { version = "0.2.0" }
clap = { version = "4.4.2", features = ["derive"] }

[dev-dependencies]
criterion = "0.5.1"

[features]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate"]
mkl = ["candle-core/mkl", "candle-nn/mkl"]

[[bench]]
name = "bench_softmax"
harness = false
