[package]
name = "speedy-softmax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = { version = "0.2.0" }
candle-nn = { version = "0.2.0" }
clap = { version = "4.4.2", features = ["derive"] }

[features]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate"]
mkl = ["candle-core/mkl", "candle-nn/mkl"]
