name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose 2>&1
    - name: Unit tests
      run: cargo test --verbose 2>&1

  code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pre-commit checks
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
    - name: Clippy (linter)
      run: cargo clippy -- -D warnings 2>&1
    - name: Check formatting
      run: cargo fmt -- --check 2>&1

  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Benchmarks
      run: cargo bench 2>&1
    