name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose
    - name: Unit tests
      run: cargo test --verbose

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy (linter)
      run: cargo clippy
    - name: Formatting
      run: cargo fmt

  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Benchmarks
      run: cargo bench